/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package LRUCache

import kotlin.test.Test
import kotlin.test.assertEquals

class LibraryTest {
    @Test fun getNotExist() {
        val cache = LRUCache(1)

        assertEquals(-1, cache.get(1))
    }

    @Test fun testPut() {
        val cache = LRUCache(1)
        cache.put(1, 1);

        assertEquals(1, cache.get(1))
    }

    @Test fun testPut2() {
        val cache = LRUCache(1)
        cache.put(1, 1)
        assertEquals(1, cache.get(1))

        cache.put(2, 2)
        assertEquals(2, cache.get(2))
        assertEquals(-1, cache.get(1))
    }

    @Test fun testPut3() {
        val cache = LRUCache(2)
        cache.put(1, 1);
        cache.put(2, 2);
        assertEquals(1, cache.get(1))
        cache.put(3, 3)

        assertEquals(-1, cache.get(2))
    }
}
