/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package LRUCache

import kotlin.test.Test
import kotlin.test.assertEquals

class LibraryTest {
    @Test fun getNotExist() {
        val cache = LRUCache(1)

        assertEquals(cache.get(1), -1)
    }
}
