/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package LRUCache

class LRUCache(capacity: Int) {
    fun get(key: Int): Int {
        return -1
    }

    fun put(key: Int, value: Int) {

    }
}

